### ISSUE TITLE
[feature request] option to use external downloader for videos

### ISSUE THREAD

**Issue by sideloading** [patrickkfkan/patreon-dl#19]
yt-dlp allows the download of enhanced bitrate without requiring/passing premium cookies from a youtube account.

having the ability to specify the downloader (optional path with the executable) would be great.

**Comment by patrickkfkan** [comment]
Implemented in v1.6.0:

```
- Add external downloader support for embedded videos
```

If you have `yt-dlp` installed and in your PATH, you can just add the following lines to your config file:

```
[embed.downloader.youtube]
exec = yt-dlp -o "{dest.dir}/%(title)s.%(ext)s" "{embed.url}"
```

`patreon-dl` should now use `yt-dlp` instead of its built-in downloader for embedded YouTube vids.

Please help test it.

Embedded Vimeo also supported too, although somewhat experimental. Refer to the [example config](https://github.com/patrickkfkan/patreon-dl/blob/1ca05402c14228cd2c21fd656f821ce3cdbda91c/example-embed.conf).
