### ISSUE TITLE
Post preview media still downloaded even if custom config set otherwise

### ISSUE THREAD

**Issue by RowanSkie** [patrickkfkan/patreon-dl#34]
So I have created my own config to set this specifically:
```conf
# The type of preview media to download, if available.
#
# General values:
# - 1: download all types of preview media
# - 0: do not download preview media
#
# Specific types:
# - "image" - download image preview(s)
# - "video" - download video preview
# - "audio" - download audio preview
#
# For specific types, you can set multiple values by separating them with a
# comma. E.g. "image, video" will download image and video previews, but skip
# audio preview.
#
# Default: 1
preview.media =0
```
However, it doesn't work, and the downloader still downloads preview posts.

**Comment by patrickkfkan** [comment]
The relevant setting is `locked.content` (set it to `0`)

**Comment by RowanSkie** [comment]
Wait, what does `preview.media` do then?

**Comment by patrickkfkan** [comment]
`locked.content` tells the downloader whether to download a locked post (preview).

If `locked.content` is set to true, `preview.media` tells the downloader whether it should download any contained images, videos, etc. 

In hindsight, I should have named this `locked.content.media` instead of `preview.media`, but oh well...
