### ISSUE TITLE
Filtering download

### ISSUE THREAD

**Issue by dsakura** [patrickkfkan/patreon-dl#6]
First, many thanks, works great. But have someway to download just the posts with attachments?

Thanks again

**Comment by patrickkfkan** [comment]
Currently no, but this is a good idea. I'll consider adding a filter criteria in the next version.

**Comment by dsakura** [comment]
Great, thank you very much, I tried to create a script to delete posts without attachments, but I was unsuccessful and lost all content lol. I will have to download everything again. When checking not to download preview, posts that have preview and attachments will be downloaded, correct?
Thanks

**Comment by patrickkfkan** [comment]
What I have in mind is a config option like  `post.has = attachment`, which will cause `patreon-dl` to process only posts that have attachments. Then there is an existing option `content.media`, which I intend to expand to allow specifying which media type to download, as well as `preview.media`. So, if your config has this:
```
[include]
post.has = attachment    // Process only posts that have attachment. Possible values: image; audio; video; attachment | any
content.media = attachment; image  // Download images and attachment in said posts. Possible values: image; audio; video; attachment | 0 | 1
preview.media =  0 // Do not download preview media. Possible values:  image; audio; video | 0 | 1
```
Then `patreon-dl` will process posts that have attachment, and for each such post it will download images and attachments. Preview media will not be downloaded because `preview.media = 0`.

**Comment by dsakura** [comment]
Perfect, many thanks! Great job!

**Comment by dsakura** [comment]
Sorry the delay, I'll test it. Many thanks!
